name: Testes pós commit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  mobile-tests:
    runs-on: ubuntu-latest

    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

    steps:
    - name: Validação de repositório
      uses: actions/checkout@v4

    - name: Configurando Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Instalando dependências
      run: npm ci

    - name: Ajustar permissão do wdio
      run: chmod +x ./node_modules/.bin/wdio

    - name: Executando testes
      run: npm run test:mobile

    - name: Gerando Relatorio
      run: npm run postreport

    - name: Upload do relatorio
      uses: actions/upload-artifact@v4
      with:
        name: mochawesome-html-report
        path: reports/mochawesome/