name: Testes pós commit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Validação de repositório
      uses: actions/checkout@v2

    - name: Configurando Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Instalando dependências
      run: |
        npm install
        npm ci

    - name: Install Appium 2.x + UiAutomator2 driver
      run: |
        npm install -g appium@latest
        appium driver install uiautomator2 || true

    - name: Start Appium server
      run: |
        appium --log-timestamp --base-path /wd/hub --port 4723 &   # sobe em background
        npx wait-on tcp:4723        

    - name: Start Emulator (API 34)
      uses: ReactiveCircus/android-emulator-runner@v2
      with:
        api-level: 34
        arch: x86_64
        profile: pixel_6
        target: google_apis
        disable-animations: true
        emulator-options: "-no-window"

    - name: Run E2E tests
      run: npm run ci:test

    - name: Gerar relatório HTML
      run: |
        mkdir -p reports
        cp -r ./reports-html/* reports/

    - name: Upload relatórios
      uses: actions/upload-artifact@v4
      with:
        name: e2e-report
        path: reports
