name: Testes pós commit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e-android:
    runs-on: ubuntu-latest       # mantém Ubuntu

    steps:
    # 1 ▸ Checkout
    - uses: actions/checkout@v4

    # 2 ▸ Node 18
    - uses: actions/setup-node@v4
      with:
        node-version: 18

    # 3 ▸ Dependências
    - name: Instalar dependências
      run: npm ci

    # 4 ▸ Emulador ARM + Testes
    - name: Start Emulator (API 30-ARM) e executar testes
      uses: ReactiveCircus/android-emulator-runner@v2
      with:
        api-level: 30                 # API 30 é mais leve; ajuste se precisar
        arch: arm64-v8a               # ✅ roda sem KVM
        profile: Nexus 5              # perfil leve
        target: google_apis
        disable-animations: true
        emulator-options: "-no-window"
        script: |
          echo "⌛ Aguardando boot completo..."
          adb wait-for-device
          until adb shell getprop sys.boot_completed | grep -m 1 '1'; do
            sleep 5
          done
          echo "✅ Emulador pronto!"
          npm run ci:test

    # 5 ▸ Relatório (opcional)
    - name: Gerar relatório HTML
      if: always()                   # ainda gera mesmo se teste falhar
      run: |
        mkdir -p reports
        cp -r ./reports-html/* reports/ || true

    - name: Upload relatórios
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: e2e-report
        path: reports