name: Testes pós commit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e-android:
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Instalar dependências
      run: npm ci

    - name: Iniciar emulador + rodar testes
      uses: ReactiveCircus/android-emulator-runner@v2
      with:
        api-level: 30
        arch: x86_64                 # volta pro x86
        profile: Nexus 5
        target: google_apis
        disable-animations: true
        emulator-options: "-no-window"
        script: |
          echo "⌛ Aguardando boot do emulador..."
          adb wait-for-device
          until adb shell getprop sys.boot_completed | grep -m 1 '1'; do
            sleep 5
          done
          echo "✅ Emulador pronto!"
          npm run ci:test

    # 5 ▸ Relatório (opcional)
    - name: Gerar relatório HTML
      if: always()                   # ainda gera mesmo se teste falhar
      run: |
        mkdir -p reports
        cp -r ./reports-html/* reports/ || true

    - name: Upload relatórios
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: e2e-report
        path: reports