name: Mobile CI – Appium + BrowserStack

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  mobile-tests:
    runs-on: ubuntu-latest

    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: npm

    - name: Instalar dependências
      run: npm ci

    - name: Ajustar permissão do wdio
      run: chmod +x ./node_modules/.bin/wdio

    - name: Executar testes mobile no BrowserStack
      run: npm run test:mobile

    - name: Gerar relatório HTML do Mochawesome
      run: npm run postreport

    - name: Upload do Relatório HTML
      uses: actions/upload-artifact@v4
      with:
        name: mochawesome-html-report
        path: reports/mochawesome/