name: Mobile CI – Appium + BrowserStack

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  mobile-tests:
    runs-on: ubuntu-latest

    # Segredos criados em Settings ▸ Secrets and variables ▸ Actions
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

    steps:
    # 1) Obtém o código do repositório
    - name: Checkout
      uses: actions/checkout@v4

    # 2) Prepara o Node e habilita cache automático do npm
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: npm

    # 3) Instala dependências declaradas no package.json
    - name: Instalar dependências
      run: npm ci

    # 4) Garante permissão de execução ao binário do WebdriverIO CLI
    - name: Ajustar permissão do wdio
      run: chmod +x ./node_modules/.bin/wdio

    # 5) Executa os testes — script definido em "scripts.test:mobile"
    - name: Executar testes mobile no BrowserStack
      run: npm run test:mobile

    - name: Gerar relatório HTML do Mochawesome
      run: npm run postreport

    - name: Upload do Relatório HTML
      uses: actions/upload-artifact@v4
      with:
        name: mochawesome-html-report
        path: reports/mochawesome/